name: java&git-vers
on:
  branch_protection_rule:
    types:
      - edited
jobs:
  example-job:
   runs-on: myselfrun-1
   steps:
     - name: Run build script
       shell: bash
       id: execute-script
       continue-on-error: true
       run: |
          java -version
          git version
